### ISSUE TITLE
im2mesh packages dependencies 

### ISSUE THREAD

**Issue by MeryemABBAD** [cborau/im2mesh#1]
Hello, 

I am trying to install im2mesh using pip install -r requirements.txt. I use python=3.9 since I first got this error saying that some packages require python >=3.9:

ERROR: Ignored the following versions that require a different python version: 1.25.0 Requires-Python >=3.9; 1.25.0rc1 Requires-Python >=3.9; 1.25.1 Requires-Python >=3.9; 1.25.2 Requires-Python >=3.9; 1.26.0 Requires-Python <3.13,>=3.9; 1.26.0b1 Requires-Python <3.13,>=3.9; 1.26.0rc1 Requires-Python <3.13,>=3.9
ERROR: Could not find a version that satisfies the requirement open3d==0.15.1 (from versions: 0.10.0.0, 0.11.0, 0.11.1, 0.11.2, 0.12.0, 0.13.0, 0.14.1, 0.15.2, 0.16.0, 0.17.0)
ERROR: No matching distribution found for open3d==0.15.1

However, now I get another error saying that some packages need a python version <3.9.

ERROR: Ignored the following versions that require a different python version: 2.5.2 Requires-Python !=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,<3.9dev,>=2.7
ERROR: Could not find a version that satisfies the requirement open3d==0.15.1 (from versions: 0.14.1, 0.15.2, 0.16.0, 0.17.0)
ERROR: No matching distribution found for open3d==0.15.1

I also got the error about the open3d version each time. I tried to update some packages such as gmsh, or even open3d but I didn't get it to work. Could you please let me know if there have been any updates on the packages versions?

Thank you very much! 

Best regards,

Meryem

**Comment by MeryemABBAD** [comment]
UPDATE: 

I tried to install each package independently (open3d in version 0.15.2). Everything seemed to be properly installed. 

However, when I try to run the second example using :

python main.py -b --path "./examples/ex2_pelvis/input/pelvis.nii" --format "nifti" --n_interp 5 --mask_id 0 --smooth_slices  --target_faces 50000 --sampling_factor 0.1 --min_mesh_size 5.0 --max_mesh_size 5.0 --output_dir "./examples/ex2_pelvis/output" --export_vtk --laplacian_smoothing

I get the following error: 
Traceback (most recent call last):
  File ./im2mesh/im2mesh/main.py", line 14, in <module>
    import formatwriter as fmt_w
  File "./im2mesh/im2mesh/formatwriter.py", line 3, in <module>
    import gmsh
  File "./miniconda3/envs/im2mesh_env_python39/lib/python3.9/site-packages/gmsh.py", line 53, in <module>
    lib = CDLL(libpath)
  File "./miniconda3/envs/im2mesh_env_python39/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libGLU.so.1: cannot open shared object file: No such file or directory


do you have an idea about how to solve this issue?

Thank you very much for your help.

Meryem

**Comment by cborau** [comment]
Hi Meryem, 
Open3d is apparently giving some errors even following the instructions on their website. In any case, I'm not able to reproduce your second issue. Have you tried creating a fresh environment? 
I just tried this on a clean PC (nothing previously installed) and it worked (even the open3d part):
```
conda create env im2mesh_env
conda activate im2mesh_env
//Navigate to the path you cloned the repo
pip install -r requirements.txt
```

**Comment by MeryemABBAD** [comment]
Hi ! 

Thank you very much for your answer. Yes, I work with conda environments as well. Since I tried to install it on an HPC the only problem I can think of is the GUI part that will not work on the HPC (I think).

Thank you !

**Comment by cborau** [comment]
Mmm, but if you are using the batch-running option (which you are) and you are not setting --view_pcd to true, there should not be any user interface nor window popping up. If I had to guess, since you installed the required packages indepentenly, I would bet there is some nasty incompatibility between them. As I said before, I would try installing everything in a fresh environment using the exact versions listed in the requirements file.

**Comment by dsdm0** [comment]
Hello Meryem!

First of all, thenk you for your interest on our Python package.
Since you're trying to install im2mesh on a HPC I assume that you're working with Linux, right? That's why you had the first error regarding the open3d version: only open3d 0.15.2 is available for Linux distros. We should state that our library has been developed for W10 OS, although we have previously installed it on a HPC using Linux.
Anyway, you may need to install the libGLu packages manually. Check this link: https://askubuntu.com/questions/386281/error-while-loading-shared-libraries-libglu-so-1
Let us know if this solves your issue.

Best regards,
Diego
